version: "3.9"
    
services:
  machine_owner_wp:
    container_name: machine_owner_wp
    # image: wordpress:latest
    build: .
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8000:80"
    restart: always
    networks:
      - mysqlnet
    environment:
      WORDPRESS_DB_HOST: globalmysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: machine_owner
      WORDPRESS_DEBUG: 1
volumes:
  db_data: {}

networks: 
  mysqlnet: 
    external: 
      name: mysqlnet